; 업로드 전 src/main.cpp 상단 MODULE_SERIAL 만 g1 / g2 등으로 변경
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
