services:
  backend:
    restart: always # 꺼지면 재시작
    build: ./backend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    env_file:
      - ./backend/.env.production
    environment:
      DB_URL: ${DB_URL:-jdbc:mysql://host.docker.internal:3306/ecolens?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8}
      DB_USERNAME: ${DB_USERNAME:-gwon}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - global_network


  frontend:
    restart: always # 꺼지면 재시작
    build: ./frontend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    ports:
      - "5173:5173"
    networks:
      - global_network
  


networks:
  global_network:
    external: true