services:
  backend:
    container_name: ecolens-backend
    restart: always # 꺼지면 재시작
    build: ./backend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    env_file:
      - ./backend/.env.production
    ports:
      - "8080:8080"
    networks:
      - global_network


  frontend:
    container_name: ecolens-frontend
    restart: always # 꺼지면 재시작
    build: ./frontend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    ports:
      - "5173:5173"
    networks:
      - global_network
  


networks:
  global_network:
    external: true